### ISSUE TITLE
Masses d'aigua

### ISSUE THREAD

**Issue by sofialog** [geraldo/geoparc-turisme#17]
- [x] Afegir capes d'embassaments i llacs
- [x] Controlar aquestes capes per escales (només etiqueta)

**Comment by sofialog** [comment]
Per revisar que estigui ben fet

**Comment by geraldo** [comment]
Ahora mismo aparecen repetidas veces. No se si se puede arreglar desde QGIS, si no luego añado un buffer al activar el Mapproxy para este proyecto.

**Comment by geraldo** [comment]
Ok, arreglado con un buffer en el cache de mapproxy:
```
  geoparc-turisme_group_masses_daigua:
    grids: [webmercator]
    sources: [geoparc-turisme_group_masses_daigua]
    meta_size: [5,5]
    meta_buffer: 256
```
